---
title: Brentley’s Blog
description: Musings of a mobile software engineer.
copyrightYear: 2015–2022
url: https://brentley.dev
gitHubURL: https://github.com/brentleyjones/brentley.dev
author: Brentley Jones
email: contact@brentleyjones.com
