---
title: Brentley Jones
description: Musings of a mobile software engineer.
copyright: © 2015–2020 Brentley Jones
url: https://brentley.dev
gitHubURL: https://github.com/brentleyjones/brentley.dev
author: Brentley Jones
email: contact@brentleyjones.com
