---
title: Brentley’s Blog
description: Musings of a build engineer.
copyrightYear: 2015–2024
url: https://brentley.dev
gitHubURL: https://github.com/brentleyjones/brentley.dev
author: Brentley Jones
email: contact@brentleyjones.com
